

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

// ----------- STATS ------------ //
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STAT_HEALTH)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_STAT_STAMINA)

// ----------- WEAPONS ------------ //
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_WEAPON_SMG)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_WEAPON_PISTOL)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_WEAPON_SHOTGUN)
