#include "CHGameplayTagDefines.h"

UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_STAT_HEALTH, "Stats.Health", "");
UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_STAT_STAMINA, "Stats.Stamina", "");
UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_WEAPON_SMG, "Weapons.SMG", "");
UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_WEAPON_PISTOL, "Weapons.Pistol", "");
UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_WEAPON_SHOTGUN, "Weapons.Shotgun", "");